### ISSUE TITLE
Intel MPX is deprecated

### ISSUE THREAD

**Issue by skull-squadron** [tudinfse/intel_mpx_explained#1]
It might be worth throwing a banner notice that MPX may still exist in the architecture, but [FLOSS support for it has declined significantly.](https://www.phoronix.com/scan.php?page=news_item&px=Intel-MPX-Is-Dead)

**Comment by OleksiiOleksenko** [comment]
Not sure if it's that important for the results of an experimental study, but ok, why not. Will do.

Thanks for reminding.
